services:
  - mysql

variables:
  MYSQL_DATABASE: library_test
  MYSQL_ROOT_PASSWORD: TestPassword

build:
  tags:
  - docker-gradle

  script:
  - SPRING_PROFILES_ACTIVE=test ./gradlew build

test:
  tags:
  - docker-gradle

  script:
  - SPRING_PROFILES_ACTIVE=test ./gradlew test