dist: xenial
language: java
sudo: false

jdk:
  - openjdk8

notifications: # 每次构建的时候是否通知，如果不想收到通知，那就设置false吧(email: false)
  email:
    recipients:
    - hexileee@gmail.com
  on_success: change
  on_failure: always

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE library_test character set UTF8mb4 collate utf8mb4_bin;'
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('TestPassword') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"

install:
  - SPRING_PROFILES_ACTIVE=travis ./gradlew build

script:
  - SPRING_PROFILES_ACTIVE=travis ./gradlew test