spring:
  datasource:
    url: jdbc:mysql://mysql/library
    username: root
    password: TestPassword
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#  jackson:
#    serialization: true

server:
  port: 8081
