spring:
  datasource:
    url: jdbc:mysql://mysql/library
    username: root
    password: TestPassword
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57InnoDBDialect
#  jackson:
#    serialization: true

server:
  port: 8081
  servlet:
    context-path: /api

swagger:
  info:
    version: 1.0
    title: Library Management System
    description: LMS API doc
    license: MIT
    licenseUrl: https://github.com/Hexilee/LMS-backend/blob/master/LICENSE
    contactName: Hexi
    contactURL: hexilee.me
    contactEmail: hexileee@gmail.com
security:
  bcrypt:
    rounds: 10
  jwt:
    expiration: 3600
    secret: gTGWdOqlEWwLOq7wPZ3gEHVq3ehnSQvrgGuGvC9YBFjrcbEbq0vw3KBqoM4dzuua3l3l3KTHmBQrVouOHpRBX33BDgs3OK3BJD5b